### ISSUE TITLE
Linux 15.1 errors on language pack download

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#298]
On Ubuntu 14 LTS testing the recent 15.1 installations (not upgrade) the following error is encountered when trying to update or install language packs both through UI and manually using the kalite command. Replicated by @aronasorman 
![2015-12-03_13-15-28](https://cloud.githubusercontent.com/assets/4349806/11574110/e30e8028-99c6-11e5-894a-ce1a340b36e1.png)

```
ed@ed-VirtualBox:~$ kalite manage languagepackdownload -lde --commandline
INFO:kalite:Downloading language pack for lang_name=Deutsch, software_version=0.15
INFO:kalite:Downloading language pack 'de'
INFO:kalite:Retrieving language pack: de
INFO:kalite:Unpacking language pack 'de'
INFO:kalite:Unpacking new translations
WARNING:py.warnings:/usr/lib/python2.7/dist-packages/kalite/updates/management/commands/languagepackdownload.py:142: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  raise type(e), type(e)(e.message + _("Language pack corrupted. Please try downloading the language pack again in a few minutes."))

INFO:kalite:Error: File is not a zip fileLanguage pack corrupted. Please try downloading the language pack again in a few minutes.
INFO:kalite:Cancelling process languagepackdownload
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/share/kalite/python-packages/fle_utils/django_utils/command.py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "/usr/share/kalite/python-packages/fle_utils/chronograph/management/croncommand.py", line 38, in execute
    super(CronCommand, self).execute(*args, **kwargs)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/kalite/updates/management/commands/languagepackdownload.py", line 85, in handle
    unpack_language(lang_code, zip_filepath=zip_filepath)
  File "/usr/lib/python2.7/dist-packages/kalite/updates/management/commands/languagepackdownload.py", line 142, in unpack_language
    raise type(e), type(e)(e.message + _("Language pack corrupted. Please try downloading the language pack again in a few minutes."))
BadZipfile: File is not a zip fileLanguage pack corrupted. Please try downloading the language pack again in a few minutes.
ed@ed-VirtualBox:~$ 
```

**Comment by aronasorman** [comment]
Not just a problem on Linux. It's in the Mac as well.

**Comment by EdDixon** [comment]
Good to know I created a seperate issue with other problems discovered working with the language packs that I suspected where main repo related and referenced this there or at least tried to please make sure I did that right or move this to the repo as needed. Thanks,
https://github.com/learningequality/ka-lite/issues/4727

**Comment by EdDixon** [comment]
Just verified this also exists on the recent Windows and MAC, 0.15.1 builds as well so moving screen shots and the traceback to the main repo issue and closing here. Please address the issue in the main repo. 
https://github.com/learningequality/ka-lite/issues/4727
Thanks,
