### ISSUE TITLE
Contentpack error on Windows installer (DatabaseError: no such table: updates_updateprogresslog)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/installers#371]
## Summary

It seems necessary to run the server at least once in order to be able to run `kalite manage retrievecontentpack local en` and not get db errors. After a fresh install on Win7 where I tried `kalite manage retrievecontentpack local en` prior to running server for the first time and got errors below. I run the server once, and re-tried  `kalite manage retrievecontentpack` and it finished OK. 

I then re-tested on a fresh VM and paid more attention on `cmd.exe` window during install, and there was a an error but too brief for me to see before the window closed and installer finished. The same happened with 165 today but this time I saved the output of local command (see below).  

## Branch or installer

Discovered yesterday on build 161, confirmed today on 165, Windows 7. Latest contentpack from Bamboo.

## Traceback or server.log snippet

```
C:\Python27\Scripts>kalite manage retrievecontentpack local en en.zip
C:\Python27\Scripts\kalite:129: RuntimeWarning: Could not determine Python in yo
ur path, defaulting to C:\Python27\python.exe
  warnings.warn("Could not determine Python in your path, defaulting to {0:s}".f
ormat(python_executable), RuntimeWarning)
[WARNING] [2016-03-02 10:58:43,563] kalite: Channel khan does not exist.
Traceback (most recent call last):
  File "C:\Python27\share\kalite\python-packages\django\core\management\base.py"
, line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\Python27\share\kalite\python-packages\fle_utils\django_utils\command.
py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "C:\Python27\share\kalite\python-packages\django\core\management\base.py"
, line 263, in execute
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\kalite\distributed\management\commands\ret
rievecontentpack.py", line 76, in handle
    self.setup(options)
  File "C:\Python27\lib\site-packages\kalite\updates\management\commands\classes
.py", line 55, in setup
    self.progress_log = UpdateProgressLog.get_active_log(process_name=self.proce
ss_name)
  File "C:\Python27\lib\site-packages\kalite\updates\models.py", line 168, in ge
t_active_log
    if logs.count() > 0:
  File "C:\Python27\share\kalite\python-packages\django\db\models\query.py", lin
e 372, in count
    return self.query.get_count(using=self.db)
  File "C:\Python27\share\kalite\python-packages\django\db\models\sql\query.py",
 line 423, in get_count
    number = obj.get_aggregation(using=using)[None]
  File "C:\Python27\share\kalite\python-packages\django\db\models\sql\query.py",
 line 389, in get_aggregation
    result = query.get_compiler(using).execute_sql(SINGLE)
  File "C:\Python27\share\kalite\python-packages\django\db\models\sql\compiler.p
y", line 840, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\share\kalite\python-packages\django\db\backends\sqlite3\base
.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.ex
c_info()[2])
  File "C:\Python27\share\kalite\python-packages\django\db\backends\sqlite3\base
.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: updates_updateprogresslog

C:\Python27\Scripts>
```

## How to reproduce

1. Install KA Lite.
1. Do not start the server.
1. Run `C:\Python27\Scripts>kalite manage retrievecontentpack local en en.zip`

## Real-life consequences
Installation without properly installed content pack.

@MCGallaspy

**Comment by MCGallaspy** [comment]
Thanks for the report!

**Comment by radinamatic** [comment]
Update, hope it helps: 

Doing the same on XP, gave a different error:

```
C:\Python27\Scripts>kalite manage retrievecontentpack local en en.zip
C:\Python27\Scripts\kalite:129: RuntimeWarning: Could not determine Python in yo
ur path, defaulting to C:\Python27\python.exe
  warnings.warn("Could not determine Python in your path, defaulting to {0:s}".f
ormat(python_executable), RuntimeWarning)
Traceback (most recent call last):
  File "C:\Python27\share\kalite\kalitectl.py", line 130, in <module>
    os.mkdir(KALITE_HOME)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C
:\\Documents and Settings\\IEUser\\.kalite'

C:\Python27\Scripts>
```

**Comment by radinamatic** [comment]
Hmm... On XP running the server once before installing contentpack locally did not have the same effect. I'm still getting the same error as above, no matter which languagepack I try to install:

```
C:\Python27\Scripts>kalite manage retrievecontentpack local fr fr.zip
C:\Python27\Scripts\kalite:129: RuntimeWarning: Could not determine Python in yo
ur path, defaulting to C:\Python27\python.exe
  warnings.warn("Could not determine Python in your path, defaulting to {0:s}".f
ormat(python_executable), RuntimeWarning)
Traceback (most recent call last):
  File "C:\Python27\share\kalite\kalitectl.py", line 130, in <module>
    os.mkdir(KALITE_HOME)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C
:\\Documents and Settings\\IEUser\\.kalite'

C:\Python27\Scripts>
```

**Comment by radinamatic** [comment]
XP does seem to have an issue with contentpacks:

- they do not work correctly at install time
- they can't be installed afterwards

**Comment by radinamatic** [comment]
Difference in locales...?

On this XP:

- I installed the "bare" build 165 installer, and it had errors at the last step, too fast to see
- tried to install en.zip locally, with error 3 posts above
- tried to install contentpacks in other languages, with error 2 posts above
- installed Spanish langpack from Manage > Languages

Lot of content missing here:

![es2](https://cloud.githubusercontent.com/assets/1457929/13481683/ff416d38-e0e7-11e5-91e0-8b31df9e9720.png)

If I switch the same exercise to English:

![en2](https://cloud.githubusercontent.com/assets/1457929/13481736/71af4bc4-e0e8-11e5-82a9-64b89d8ea0e6.png)

The last error says "video", but this is an exercise.

**Comment by radinamatic** [comment]
Last try, `kalite manage unpack_assessment_zip`, same error on XP:

```
C:\Python27\Scripts>kalite manage unpack_assessment_zip /f khan_assessment.zip
C:\Python27\Scripts\kalite:129: RuntimeWarning: Could not determine Python in yo
ur path, defaulting to C:\Python27\python.exe
  warnings.warn("Could not determine Python in your path, defaulting to {0:s}".f
ormat(python_executable), RuntimeWarning)
Traceback (most recent call last):
  File "C:\Python27\share\kalite\kalitectl.py", line 130, in <module>
    os.mkdir(KALITE_HOME)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C
:\\Documents and Settings\\IEUser\\.kalite'

C:\Python27\Scripts>
```

**Comment by MCGallaspy** [comment]
Ah, I forgot that you made this report! But this is fixed in #374

**Comment by MCGallaspy** [comment]
Hm, except possbily for the issue with XP you identify.

**Comment by radinamatic** [comment]
Yes, better to leave it open until it's confirmed on XP.

**Comment by radinamatic** [comment]
Still extant on Windows 8.1 with build 176 @MCGallaspy! #374 is merged, did it make into that build?

```

C:\Python27\Scripts>kalite manage retrievecontentpack local en en.zip
C:\Python27\Scripts\kalite:129: RuntimeWarning: Could not determine Python in yo
ur path, defaulting to C:\Python27\python.exe
  warnings.warn("Could not determine Python in your path, defaulting to {0:s}".f
ormat(python_executable), RuntimeWarning)
[WARNING] [2016-03-14 07:00:57,698] kalite: Channel khan does not exist.
Traceback (most recent call last):
  File "C:\Python27\share\kalite\python-packages\django\core\management\base.py"
, line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\Python27\share\kalite\python-packages\fle_utils\django_utils\command.
py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "C:\Python27\share\kalite\python-packages\django\core\management\base.py"
, line 263, in execute
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\kalite\distributed\management\commands\ret
rievecontentpack.py", line 70, in handle
    self.setup(options)
  File "C:\Python27\lib\site-packages\kalite\updates\management\commands\classes
.py", line 55, in setup
    self.progress_log = UpdateProgressLog.get_active_log(process_name=self.proce
ss_name)
  File "C:\Python27\lib\site-packages\kalite\updates\models.py", line 168, in ge
t_active_log
    if logs.count() > 0:
  File "C:\Python27\share\kalite\python-packages\django\db\models\query.py", lin
e 372, in count
    return self.query.get_count(using=self.db)
  File "C:\Python27\share\kalite\python-packages\django\db\models\sql\query.py",
 line 423, in get_count
    number = obj.get_aggregation(using=using)[None]
  File "C:\Python27\share\kalite\python-packages\django\db\models\sql\query.py",
 line 389, in get_aggregation
    result = query.get_compiler(using).execute_sql(SINGLE)
  File "C:\Python27\share\kalite\python-packages\django\db\models\sql\compiler.p
y", line 840, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\share\kalite\python-packages\django\db\backends\sqlite3\base
.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.ex
c_info()[2])
  File "C:\Python27\share\kalite\python-packages\django\db\backends\sqlite3\base
.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: updates_updateprogresslog

C:\Python27\Scripts>
```

**Comment by MCGallaspy** [comment]
> Still extant on Windows 8.1 with build 176

Did the installer fail to unpack the content pack? Note that you shouldn't need to run the command `retrievecontentpack` yourself after installation, but if you do for some reason it *will* fail unless you include the `--foreground` option. That's the fix incorporated by #374.

**Comment by radinamatic** [comment]
Installer did not fail, it was my bad, I re-run the `retrievecontentpack` and did not include the `--foreground` option. The first try (after install, before running the server once) locally failed, second (after running server once) didn't. So I basically installed English contentpack twice... :stuck_out_tongue: 

We should document this option, for users who will install contentpacks for other languages prior to running the server, right?

**Comment by MCGallaspy** [comment]
Yes, can you open an issue on the ka-lite repo?
