### ISSUE TITLE
Cannot install pyyaml running setup.sh.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#39]
**Branch** Master
**Target** 0.14.x
**Mac OS X** Yosemite 10.10.3
**Expected Behavior** Running `setup.sh` should build the .dmg package.
**Possible Solution** Install with admin privileges like `sudo pip install pyyaml`.
**References**
* http://stackoverflow.com/questions/14261614/how-do-i-install-the-yaml-package-for-python

**Current Behavior** Running `pip install -r requirements.txt` fails inside `setup.sh` is run to build the .dmg package.  

```bash
...

81 warnings generated.

clang -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib /usr/local/opt/zlib/lib /usr/local/opt/zlib/include build/temp.macosx-10.10-x86_64-2.7/ext/_yaml.o -lyaml -o build/lib.macosx-10.10-x86_64-2.7/_yaml.so

ld: can't map file, errno=22 file '/usr/local/opt/zlib/include' for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: command 'clang' failed with exit status 1
...
```

See detailed error log.

```bash
------------------------------------------------------------
/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/bin/pip run on Mon May 11 16:05:28 2015
Requirement already satisfied (use --upgrade to upgrade): django-compressor==1.4 in ./temp/pyrun-2.7/lib/python2.7/site-packages (from -r /Users/cyril/w/fle/ka-lite/installers/osx/temp/ka-lite/requirements.txt (line 1))
Downloading/unpacking pyyaml==3.11 (from -r /Users/cyril/w/fle/ka-lite/installers/osx/temp/ka-lite/requirements.txt (line 3))
  Getting page https://pypi.python.org/simple/pyyaml/
  URLs to search for versions for pyyaml==3.11 (from -r /Users/cyril/w/fle/ka-lite/installers/osx/temp/ka-lite/requirements.txt (line 3)):
  * https://pypi.python.org/simple/pyyaml/3.11
  * https://pypi.python.org/simple/pyyaml/
  Getting page https://pypi.python.org/simple/pyyaml/3.11
  Could not fetch URL https://pypi.python.org/simple/pyyaml/3.11: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/pyyaml/3.11 when looking for download links for pyyaml==3.11 (from -r /Users/cyril/w/fle/ka-lite/installers/osx/temp/ka-lite/requirements.txt (line 3))
  Analyzing links from page https://pypi.python.org/simple/pyyaml/
    Skipping link https://pypi.python.org/packages/2.5/P/PyYAML/PyYAML-3.10.win32-py2.5.exe#md5=dfb573ab41cdfee1b2794b7a155e72e6 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.6/P/PyYAML/PyYAML-3.10.win32-py2.6.exe#md5=4c1a374cb89fa0ff43f3b94b5692edd9 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.6/P/PyYAML/PyYAML-3.11.win-amd64-py2.6.exe#md5=af7eade45dcb408473928953f430e7db (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.6/P/PyYAML/PyYAML-3.11.win32-py2.6.exe#md5=83b0f47825feac2da99b75bfbd65a3ab (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/P/PyYAML/PyYAML-3.10.win32-py2.7.exe#md5=73309e5fe73d7d84e0af3213b2c957ff (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/P/PyYAML/PyYAML-3.11.win-amd64-py2.7.exe#md5=538cd92d63068161d229cb8a65db7f23 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/P/PyYAML/PyYAML-3.11.win32-py2.7.exe#md5=d75320c7a904731d6e27418e346a92e1 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.0/P/PyYAML/PyYAML-3.10.win32-py3.0.exe#md5=0360710722fdc58e519d6a76324aa1d7 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.1/P/PyYAML/PyYAML-3.10.win32-py3.1.exe#md5=6c830441d9df703458e2f34c2e6a413a (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.1/P/PyYAML/PyYAML-3.11.win-amd64-py3.1.exe#md5=d52af84d2cd6ce9b7cfddb2c525bd957 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.1/P/PyYAML/PyYAML-3.11.win32-py3.1.exe#md5=1b3b956bbe638c50eb80273b639be692 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.2/P/PyYAML/PyYAML-3.10.win32-py3.2.exe#md5=fc582f2f46f6494a97c9cae938a19f59 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.2/P/PyYAML/PyYAML-3.11.win-amd64-py3.2.exe#md5=328bfd749ee42279b9d8a75397e9444d (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.2/P/PyYAML/PyYAML-3.11.win32-py3.2.exe#md5=b40a15302b494d0bcc79568ff38ab43c (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.3/P/PyYAML/PyYAML-3.11.win-amd64-py3.3.exe#md5=672275294ababb18794b328a24c836b4 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.3/P/PyYAML/PyYAML-3.11.win32-py3.3.exe#md5=c3990781cc999744cd21df473068f388 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.4/P/PyYAML/PyYAML-3.11.win-amd64-py3.4.exe#md5=0dfcdae003642dfdfb49d5f16ff63717 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.4/P/PyYAML/PyYAML-3.11.win32-py3.4.exe#md5=5c14b49d828766c23bb9c83d6a60aaf5 (from https://pypi.python.org/simple/pyyaml/); unknown archive format: .exe
    Found link https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.10.tar.gz#md5=74c94a383886519e9e7b3dd1ee540247 (from https://pypi.python.org/simple/pyyaml/), version: 3.10
    Found link https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.10.zip#md5=b1a2b30cdf481da4249c917c3307f129 (from https://pypi.python.org/simple/pyyaml/), version: 3.10
    Found link https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.tar.gz#md5=f50e08ef0fe55178479d3a618efe21db (from https://pypi.python.org/simple/pyyaml/), version: 3.11
    Found link https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.zip#md5=89cbc92cda979042533b640b76e6e055 (from https://pypi.python.org/simple/pyyaml/), version: 3.11
  Ignoring link https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.10.tar.gz#md5=74c94a383886519e9e7b3dd1ee540247 (from https://pypi.python.org/simple/pyyaml/), version 3.10 doesn't match ==3.11
  Ignoring link https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.10.zip#md5=b1a2b30cdf481da4249c917c3307f129 (from https://pypi.python.org/simple/pyyaml/), version 3.10 doesn't match ==3.11
  Using version 3.11 (newest of versions: 3.11, 3.11)
  Downloading from URL https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.tar.gz#md5=f50e08ef0fe55178479d3a618efe21db (from https://pypi.python.org/simple/pyyaml/)
  Running setup.py (path:/private/var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip_build_cyril/pyyaml/setup.py) egg_info for package pyyaml
    running egg_info
    creating pip-egg-info/PyYAML.egg-info
    writing pip-egg-info/PyYAML.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/PyYAML.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/PyYAML.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/PyYAML.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/PyYAML.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/PyYAML.egg-info/SOURCES.txt'
  Source in /private/var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip_build_cyril/pyyaml has version 3.11, which satisfies requirement pyyaml==3.11 (from -r /Users/cyril/w/fle/ka-lite/installers/osx/temp/ka-lite/requirements.txt (line 3))
Installing collected packages: pyyaml
  Running setup.py install for pyyaml
    Running command /Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/bin/pyrun -c "import setuptools, tokenize;__file__='/private/var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip_build_cyril/pyyaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip-BcICLf-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.5-x86_64-2.7
    creating build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/composer.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/constructor.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/cyaml.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/dumper.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/emitter.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/error.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/events.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/loader.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/nodes.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/parser.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/reader.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/representer.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/resolver.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/scanner.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/serializer.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    copying lib/yaml/tokens.py -> build/lib.macosx-10.5-x86_64-2.7/yaml
    running build_ext
    creating build/temp.macosx-10.5-x86_64-2.7
    checking if libyaml is compilable
    gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes /usr/local/opt/zlib/include -I/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/include/python2.7 -c build/temp.macosx-10.5-x86_64-2.7/check_libyaml.c -o build/temp.macosx-10.5-x86_64-2.7/check_libyaml.o
    clang: warning: /usr/local/opt/zlib/include: 'linker' input unused
    checking if libyaml is linkable
    gcc build/temp.macosx-10.5-x86_64-2.7/check_libyaml.o -lyaml -o build/temp.macosx-10.5-x86_64-2.7/check_libyaml
    building '_yaml' extension
    creating build/temp.macosx-10.5-x86_64-2.7/ext
    gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes /usr/local/opt/zlib/include -I/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/include/python2.7 -c ext/_yaml.c -o build/temp.macosx-10.5-x86_64-2.7/ext/_yaml.o
    clang: warning: /usr/local/opt/zlib/include: 'linker' input unused
    In file included from ext/_yaml.c:343:
    ext/_yaml.h:6:9: warning: 'PyUnicode_FromString' macro redefined [-Wmacro-redefined]
    #define PyUnicode_FromString(s) PyUnicode_DecodeUTF8((s), strlen(s), "strict")
            ^
    /Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/include/python2.7/unicodeobject.h:194:10: note: previous definition is here
    # define PyUnicode_FromString PyUnicodeUCS2_FromString
             ^

    ext/_yaml.c:9688:38: warning: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        __pyx_t_9 = PyUnicode_FromString(__pyx_v_self->parsed_event.data.scalar.tag); if (unlikely(!__pyx_t_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 804; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ext/_yaml.h:6:66: note: expanded from macro 'PyUnicode_FromString'
    #define PyUnicode_FromString(s) PyUnicode_DecodeUTF8((s), strlen(s), "strict")
                                                                     ^
    /usr/include/string.h:82:28: note: passing argument to parameter here
    size_t   strlen(const char *);
                                ^
    ext/_yaml.c:9688:17: warning: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        __pyx_t_9 = PyUnicode_FromString(__pyx_v_self->parsed_event.data.scalar.tag); if (unlikely(!__pyx_t_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 804; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ext/_yaml.h:6:54: note: expanded from macro 'PyUnicode_FromString'
    #define PyUnicode_FromString(s) PyUnicode_DecodeUTF8((s), strlen(s), "strict")
                                                         ^~~
    /Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/include/python2.7/unicodeobject.h:751:17: note: passing argument to parameter 'string' here
        const char *string,         /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:10128:38: warning: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        __pyx_t_2 = PyUnicode_FromString(__pyx_v_self->parsed_event.data.sequence_start.tag); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 837; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ext/_yaml.h:6:66: note: expanded from macro 'PyUnicode_FromString'
    #define PyUnicode_FromString(s) PyUnicode_DecodeUTF8((s), strlen(s), "strict")
                                                                     ^
    /usr/include/string.h:82:28: note: passing argument to parameter here
    size_t   strlen(const char *);
                                ^

...
# lots of similar errors here
...

    ext/_yaml.c:21333:32: warning: unused function '__Pyx_GetItemInt_Tuple_Fast' [-Wunused-function]
    static CYTHON_INLINE PyObject *__Pyx_GetItemInt_Tuple_Fast(PyObject *o, Py_ssize_t i,
                                   ^
    ext/_yaml.c:21718:27: warning: function '__Pyx_PyInt_As_long' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    static CYTHON_INLINE long __Pyx_PyInt_As_long(PyObject *x) {
                              ^
    81 warnings generated.
    gcc -bundle -undefined dynamic_lookup /usr/local/opt/zlib/lib /usr/local/opt/zlib/include build/temp.macosx-10.5-x86_64-2.7/ext/_yaml.o -lyaml -o build/lib.macosx-10.5-x86_64-2.7/_yaml.so
    ld: can't map file, errno=22 file '/usr/local/opt/zlib/lib' for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
    Complete output from command /Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/bin/pyrun -c "import setuptools, tokenize;__file__='/private/var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip_build_cyril/pyyaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip-BcICLf-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.macosx-10.5-x86_64-2.7

creating build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/composer.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/constructor.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/cyaml.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/dumper.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/emitter.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/error.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/events.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/loader.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/nodes.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/parser.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/reader.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/representer.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/resolver.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/scanner.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/serializer.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

copying lib/yaml/tokens.py -> build/lib.macosx-10.5-x86_64-2.7/yaml

running build_ext

creating build/temp.macosx-10.5-x86_64-2.7

checking if libyaml is compilable

gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes /usr/local/opt/zlib/include -I/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/include/python2.7 -c build/temp.macosx-10.5-x86_64-2.7/check_libyaml.c -o build/temp.macosx-10.5-x86_64-2.7/check_libyaml.o

clang: warning: /usr/local/opt/zlib/include: 'linker' input unused

checking if libyaml is linkable

gcc build/temp.macosx-10.5-x86_64-2.7/check_libyaml.o -lyaml -o build/temp.macosx-10.5-x86_64-2.7/check_libyaml

building '_yaml' extension

creating build/temp.macosx-10.5-x86_64-2.7/ext

gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -O3 -Wall -Wstrict-prototypes /usr/local/opt/zlib/include -I/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/include/python2.7 -c ext/_yaml.c -o build/temp.macosx-10.5-x86_64-2.7/ext/_yaml.o

clang: warning: /usr/local/opt/zlib/include: 'linker' input unused

In file included from ext/_yaml.c:343:

ext/_yaml.h:6:9: warning: 'PyUnicode_FromString' macro redefined [-Wmacro-redefined]

#define PyUnicode_FromString(s) PyUnicode_DecodeUTF8((s), strlen(s), "strict")

        ^

/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/include/python2.7/unicodeobject.h:194:10: note: previous definition is here

# define PyUnicode_FromString PyUnicodeUCS2_FromString

         ^

...
# lots of similar errors here
...

ext/_yaml.c:21718:27: warning: function '__Pyx_PyInt_As_long' is not needed and will not be emitted [-Wunneeded-internal-declaration]

static CYTHON_INLINE long __Pyx_PyInt_As_long(PyObject *x) {

                          ^

81 warnings generated.

gcc -bundle -undefined dynamic_lookup /usr/local/opt/zlib/lib /usr/local/opt/zlib/include build/temp.macosx-10.5-x86_64-2.7/ext/_yaml.o -lyaml -o build/lib.macosx-10.5-x86_64-2.7/_yaml.so

ld: can't map file, errno=22 file '/usr/local/opt/zlib/lib' for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
  Removing temporary dir /private/var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip_build_cyril...
Command /Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/bin/pyrun -c "import setuptools, tokenize;__file__='/private/var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip_build_cyril/pyyaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip-BcICLf-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip_build_cyril/pyyaml
Exception information:
Traceback (most recent call last):
  File "/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /Users/cyril/w/fle/ka-lite/installers/osx/temp/pyrun-2.7/bin/pyrun -c "import setuptools, tokenize;__file__='/private/var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip_build_cyril/pyyaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip-BcICLf-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/40/5c3y6nhs7tv00vv1nq5g0nvm0000gn/T/pip_build_cyril/pyyaml
```

**Comment by aronasorman** [comment]
Oh, so llvm-clang can't build pyyaml? Interesting. @ruimalheiro

**Comment by cpauya** [comment]
I will request @amodia and @arceduardvincent to try the `setup.sh` script also to verify.

I've played with my `gcc/clang` a few months ago trying to build `pyrun` - so perhaps it's borked.

**Comment by arceduardvincent** [comment]
Hello @cpauya and @aronasorman 

It seems that the `setup.sh` is working fine.
see image below. 
![screen shot 2015-05-12 at 2 05 11 pm](https://cloud.githubusercontent.com/assets/4099119/7581396/04b60772-f8b5-11e4-984d-f77d8a90fb48.png)

Then I try to verify if the requirements is installed via pip freeze in our `pyrun`.
![screen shot 2015-05-12 at 2 45 57 pm](https://cloud.githubusercontent.com/assets/4099119/7581437/b1c128e8-f8b5-11e4-9713-232e04f71659.png)

I try to validate if the `yaml` is installed in our `pyrun`.
![screen shot 2015-05-12 at 2 49 17 pm](https://cloud.githubusercontent.com/assets/4099119/7581480/1f6fdd9e-f8b6-11e4-89cd-96726ecfec07.png)

Therefore I conclude that the `setup.sh` script  is running correctly.

**Comment by amodia** [comment]
I also verified this on `Mavericks (10.9.x)` i just run `setup.sh` and it was working fine.


![screen shot 2015-05-12 at 2 53 49 pm](https://cloud.githubusercontent.com/assets/8663934/7583139/dc5d8f32-f8c5-11e4-85aa-3f69fb569448.png)



![screen shot 2015-05-12 at 2 58 09 pm](https://cloud.githubusercontent.com/assets/8663934/7583119/a831559a-f8c5-11e4-8f7e-190e781a2066.png)

**Comment by cpauya** [comment]
Thanks for verifying @arceduardvincent and @amodia!  That made me check my envs and `~/.bash_profile`.  After some digging, found that if I comment this entry, I can successfully install `pyyaml`:

> export LDFLAGS=/usr/local/opt/zlib/lib && export CPPFLAGS=/usr/local/opt/zlib/include

So I commented that out and voila!  I have successfully built pyyaml on my local.  The entry above may be remnants from other prior experiments.

```bash
...
created: /Users/cyril/w/fle/ka-lite/installers/osx/temp/output/KA-Lite Monitor.dmg
hdiutil: internet-enable: enable succeeded
Disk image done
Done!
You can now test the built installer at '/Users/cyril/w/fle/ka-lite/installers/osx/temp/output/KA-Lite Monitor.dmg'.
cyril-lappy6:osx cyril$ temp/pyrun-2.7/bin/pip freeze
django-appconf==1.0.1
django-compressor==1.4
PyYAML==3.11
six==1.9.0
cyril-lappy6:osx cyril$
```
